### PR TITLE
Add custom kobocat theme

### PR DESCRIPTION
**Pull request by boney-bun**

### CODE REVIEW

**Comment by lucernae** [comment]
Did you check that it works, @boney-bun ?
Is this PR ready now?

**Comment by boney-bun** [comment]
i've tried on a clean env in my local.
it works @lucernae 
what if we merge and give this PR a try?

**Review by lucernae — APPROVED** [review]
Sure, LGTM!

**Comment by boney-bun** [comment]
thanks @lucernae 
i'm going to merge this

**Pull request merged**
